# Generated by Django 6.0 on 2026-01-04 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_book_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='issued',
            new_name='IssuedBook',
        ),
    ]
